### ISSUE TITLE
your game fucking sucks

### ISSUE THREAD

**Issue by danil275487** [Tim7900/BloodTest#4]
make up your mind or dont do anything, retarded cunt

**Comment by Tim7900** [comment]
I know. :P

**Comment by Tim7900** [comment]
STOP YELLING AT ME HOW DO YOU LIKE IT?

**Comment by danil275487** [comment]
did you have a stroke?

**Comment by MadKamel** [comment]
This is the dumbest bloody issue I've seen in all of my days. Kindly fuck off.

**Comment by Tim7900** [comment]
Why are we argueing?

**Comment by MadKamel** [comment]
It might have something to do with the first comment.
